function res(){
  document.getElementById("username").value = " ";
  document.getElementById("useremail").value = " ";
  document.getElementById("textarea").value = " ";
 }
function giveout(){
  var user= document.getElementById("username").value;
  var emails= document.getElementById("useremail").value;
  var textareas= document.getElementById("textarea").value;
  if ((user ==="") || (emails ==="") || (textareas ==="")){
    alert("Please enter valid data");
  }else{
    alert("Thank you for getting in touch " + user);
  }
}
$(document).ready(function(){
  $("#design_i").click(function(){
    $(".design_p").toggle();
    $("#design_i").toggle();
  });
  $(".design_p").click(function(){
    $("#design_i").toggle();
    $(".design_p").toggle();
  });
  $("#dev_i").click(function(){
    $(".dev_p").toggle();
    $("#dev_i").toggle();
  });
  $(".dev_p").click(function(){
    $("#dev_i").toggle();
    $(".dev_p").toggle();
  });
  $("#do").click(function(){
    $(".pro_p").toggle();
    $("#do").toggle();
  });
  $(".pro_p").click(function(){
    $("#do").toggle();
    $(".pro_p").toggle();
  });
  $("#work4p").hide();
  $("#work4i").animate({opacity:5});
  $("#work4i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work4p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work4p").fadeOut(); 
});
$("#work3p").hide();
  $("#work3i").animate({opacity:5});
  $("#work3i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work3p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work3p").fadeOut(); 
});
$("#work2p").hide();
  $("#work2i").animate({opacity:5});
  $("#work2i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work2p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work2p").fadeOut(); 
});
$("#work1p").hide();
  $("#work1i").animate({opacity:5});
  $("#work1i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work1p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work1p").fadeOut(); 
});
$("#work5p").hide();
  $("#work5i").animate({opacity:5});
  $("#work5i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work5p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work5p").fadeOut(); 
});
$("#work6p").hide();
  $("#work6i").animate({opacity:5});
  $("#work6i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work6p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work6p").fadeOut(); 
});
$("#work7p").hide();
  $("#work7i").animate({opacity:5});
  $("#work7i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work7p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work7p").fadeOut(); 
});
$("#work8p").hide();
  $("#work8i").animate({opacity:5});
  $("#work8i").hover(function(){
      $(this).stop().animate({opacity:0.4});
      $("#work8p").fadeIn(); 
  },
  function(){
    $(this).stop().animate({opacity:1});
    $("#work8p").fadeOut(); 
});
});